---
name: cargo-deb
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3.0.2
    - id: version
      uses: docker://lpenz/ghaction-version-gen:0.9.0
    - name: install cargo-deb
      uses: actions-rs/cargo@v1.0.3
      with:
        command: install
        args: cargo-deb
    - name: cargo-deb, test only
      uses: actions-rs/cargo@v1.0.3
      if: inputs.deb && steps.version.outputs.version_commit == ''
      with:
        command: deb
    - name: cargo-deb, release
      uses: actions-rs/cargo@v1.0.3
      if: inputs.deb && steps.version.outputs.version_commit != ''
      with:
        command: deb
        args: --deb-version '${{ steps.version.outputs.version_commit }}'
    - name: show deb info
      if: inputs.deb
      run: |
        set -e -x;
        dpkg -I target/debian/*.deb
        dpkg -c target/debian/*.deb;
    - uses: actions/upload-artifact@v3.1.0
      if: inputs.deb
      with:
        name: cargo-deb
        if-no-files-found: error
        path: target/debian
