---
name: CI
on: [workflow_dispatch, push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: docker://lpenz/omnilint:0.5.2
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
        with:
          config-file: .github/config/mlc_config.json
  publish-github-release:
    needs: [omnilint, markdown-link-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.17.3
      - name: publish github release
        uses: softprops/action-gh-release@v3
        if: steps.version.outputs.version_tagged != ''
        with:
          tag_name: ${{ steps.version.outputs.version_tagged }}
          generate_release_notes: true
