---
# Copyright (C) 2022 Leandro Lisboa Penz <lpenz@lpenz.org>
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.
name: rust
on:
  workflow_call:
    inputs:
      coveralls:
        description: |
          Makes cargo-test upload test coverage data to coveralls.io
          when true.
        required: false
        type: boolean
        default: false
      codecov:
        description: |
          Makes *cargo-test* upload test coverage data to codecov.io
          when true.
        required: false
        type: boolean
        default: false
      deb:
        description: Enables cargo-deb when true.
        required: false
        type: boolean
        default: false
      dependencies_debian:
        description: |
          Dependencies as Debian packages to install; used in the
          appropriate actions if defined
        type: string
      publish_cratesio:
        description: Enables the publish-cratesio job.
        required: false
        type: boolean
        default: true
      publish_github_release:
        description: Enables the publish-github-release job.
        required: false
        type: boolean
        default: true
      publish_github_release_files:
        description: Files to publish in the github release.
        required: false
        type: string
        default: ''
      publish_packagecloud:
        description: Enables the publish-packagecloud job.
        required: false
        type: boolean
        default: false
      publish_packagecloud_repository:
        description: packagecloud repository to publish .deb.
        required: false
        type: string
        default: ''
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: false
      PACKAGECLOUD_TOKEN:
        required: false
jobs:
  # Some actions inspired by:
  # https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
  cargo-build-release:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: sudo apt-get install -y --no-install-recommends ${{ inputs.dependencies_debian }}
        if: inputs.dependencies_debian
      - uses: actions/checkout@v3.0.2
      - name: cargo build --release
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: cargo-build-release
          if-no-files-found: error
          path: target/release
  cargo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: cargo check
        uses: actions-rs/cargo@v1.0.3
        with:
          command: check
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: cargo test with coverage
        id: coverage
        uses: docker://lpenz/ghaction-rust-coverage:0.10.0
        with:
          dependencies_debian: ${{ inputs.dependencies_debian }}
      - name: upload coverage data to coveralls
        uses: coverallsapp/github-action@1.1.3
        if: inputs.coveralls
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
      - name: upload coverage data to codecov
        uses: codecov/codecov-action@v3.1.0
        if: inputs.codecov
        with:
          files: ${{ steps.coverage.outputs.report }}
          fail_ci_if_error: true
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: rust fmt --all -- --check
        uses: actions-rs/cargo@v1.0.3
        with:
          command: fmt
          args: --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  cargo-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/cargo-deb
        if: inputs.deb
  publish-cratesio:
    needs: [ cargo-build-release, cargo-check, cargo-test, rustfmt,
             clippy, cargo-audit, cargo-deb ]
    if: inputs.publish_cratesio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.9.0
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true
      - name: publish crate on crates.io
        uses: katyo/publish-crates@v1
        if: steps.version.outputs.version_tagged != ''
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish-packagecloud:
    needs: [ cargo-build-release, cargo-check, cargo-test, rustfmt,
             clippy, cargo-audit, cargo-deb ]
    if: inputs.publish_packagecloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.9.0
      - name: download cargo-deb
        uses: actions/download-artifact@v3.0.0
        if: inputs.deb
        with:
          name: cargo-deb
          path: target/release
      - name: publish deb on packagecloud
        uses: docker://lpenz/ghaction-packagecloud:0.4
        if: steps.version.outputs.version_tagged != ''
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        with:
          repository: ${{ inputs.publish_packagecloud_repository }}
  publish-github-release:
    needs: [ cargo-build-release, cargo-check, cargo-test, rustfmt,
             clippy, cargo-audit, cargo-deb ]
    if: inputs.publish_github_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.9.0
      - name: download cargo-build-release
        uses: actions/download-artifact@v3.0.0
        with:
          name: cargo-build-release
          path: target/release
      - name: download cargo-deb
        uses: actions/download-artifact@v3.0.0
        if: inputs.deb
        with:
          name: cargo-deb
          path: target/debian
      - name: list all files
        run: find . -type f
      - name: publish github release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        if: steps.version.outputs.version_tagged != ''
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            target/debian/*.deb
            ${{ inputs.publish_github_release_files }}
