---
# Copyright (C) 2022 Leandro Lisboa Penz <lpenz@lpenz.org>
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.
name: rust
on:
  workflow_call:
    inputs:
      deb:
        required: false
        type: boolean
        default: false
      coveralls:
        required: false
        type: boolean
        default: false
      codecov:
        required: false
        type: boolean
        default: false
      packagecloud:
        required: false
        type: boolean
        default: false
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: false
      PACKAGECLOUD_TOKEN:
        required: false
jobs:
  # Some actions inspired by:
  # https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
  cargo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: coverage
        uses: docker://lpenz/ghaction-rust-coverage:0.8.0
      - uses: coverallsapp/github-action@v1.1.2
        if: inputs.coveralls
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
      - uses: codecov/codecov-action@v3
        if: inputs.codecov
        with:
          files: ${{ steps.coverage.outputs.report }}
          fail_ci_if_error: true
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  cargo-deb:
    if: inputs.deb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.9.0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb
      - name: Copy manual
        run: find target -name '*.[0-9]' -exec cp -vt . {} +
      - uses: actions-rs/cargo@v1
        if: steps.version.outputs.version_commit != ''
        with:
          command: deb
          args: --deb-version '${{ steps.version.outputs.version_commit }}'
      - uses: actions/upload-artifact@v2
        if: steps.version.outputs.version_commit != ''
        with:
          if-no-files-found: error
          path: |
            target/debian/*.deb
            target/release/*
  publish-crate:
    needs: [ cargo-check, cargo-test, rustfmt, clippy, cargo-audit ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.9.0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        if: steps.version.outputs.version_tagged != '' && env.CARGO_REGISTRY_TOKEN != ''
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  packagecloud:
    needs: [ cargo-deb, publish-crate ]
    if: inputs.packagecloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.9.0
      - uses: actions/download-artifact@v2
        if: steps.version.outputs.version_tagged != ''
      - uses: docker://lpenz/ghaction-packagecloud:0.4
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        if: steps.version.outputs.version_tagged != '' && env.PACKAGECLOUD_TOKEN != ''
        with:
          repository: debian/debian/bullseye
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        if: steps.version.outputs.version_tagged != '' && env.PACKAGECLOUD_TOKEN != ''
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            artifact/debian/*.deb
            artifact/release/*
